### ISSUE TITLE
gem install pkg/fftw-0.1.3.gem d fails to find nmatrix

### ISSUE THREAD

**Issue by thisMagpie** [thisMagpie/fftw#23]
Although running the command

```
bundle exec rake compile
```

works fine, it doesn't work for

```
gem install pkg/fftw-0.1.3.gem
```

The log with the error is:

```
/home/magpie/.rvm/rubies/ruby-2.1.2/bin/ruby extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/home/magpie/.rvm/rubies/ruby-2.1.2/bin/ruby
/home/magpie/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- nmatrix (LoadError)
    from /home/magpie/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from extconf.rb:3:in `<main>'

extconf failed, exit code 1
```

**Comment by thisMagpie** [comment]
This seems to be fixed now. Not sure why.
